---
title: "Quantifying cryptic transcription in C.elegans (regression based)"
format:
  html:
    code-fold: true
---


```{r}
library(tidyverse)
library(tximport)
library(readr)
library(rtracklayer)
library(ggplot2)


# This code junk for filtering salmon major transcripts (important for quantifying cryptic transcription later on)

samples <- c(
  "wt", "wt", "wt", "ama1", "ama1", "ama1", 
  "daf2", "daf2", "daf2", "wtday1", "wtday1", "wtday1", 
  "ama1day1", "ama1day1", "ama1day1"
)

names(samples) <- c(
  "K002000093_54873", "K002000093_54875", "K002000093_54877", 
  "K002000093_54879", "K002000093_54881", "K002000093_54883", 
  "K002000093_54885", "K002000093_54887", "K002000093_54889", 
  "K002000244_89704", "K002000244_89706", "K002000244_89708", 
  "K002000244_89710", "K002000244_89712", "K002000244_89714"
)

samples_dict <- list(c("K002000093_54873", "K002000093_54875", "K002000093_54877"),
                c("K002000093_54879", "K002000093_54881", "K002000093_54883"),
                c("K002000093_54885", "K002000093_54887", "K002000093_54889"),
                c("K002000244_89704", "K002000244_89706", "K002000244_89708"),
                c("K002000244_89710", "K002000244_89712", "K002000244_89714"))



names(samples_dict) <- unique(samples)


common_path <- '/cellfile/datapublic/ahyseni/cryption/c.elegans/docker/salmon_quant/output'

# reading in the salmon quantification files, e.g.: /cellfile/datapublic/ahyseni/cryption/c.elegans/docker/salmon_quant/output/wt/K002000093_54873/quant.sf

quant_filepaths <- file.path(common_path, samples, names(samples), "quant.sf")

quant_filepaths
# load the files in one matirx
all_quant_files <- tximport(quant_filepaths, type = "salmon", txOut = TRUE)

names(all_quant_files)

# extract only TMP vals
all_TPMs <- all_quant_files$abundance
all_lengths <- all_quant_files$length

colnames(all_TPMs) <- paste0(names(samples), '_', samples)
colnames(all_lengths) <- paste0(names(samples), '_', samples)

long_transcripts <- as.data.frame(all_lengths) %>%
  mutate(mean_length = rowMeans(across(starts_with("K")))) %>%
  filter(mean_length > 1000)


# load gtf file
gtf_filepath <- '/cellfile/datapublic/ahyseni/cryption/c.elegans/data/reference_omes/Caenorhabditis_elegans.WBcel235.90.gtf'
gtf_data <- import(gtf_filepath)
gtf_df <- as.data.frame(mcols(gtf_data))
gtf_df_with_index <- readGFF(gtf_filepath)


# extract relevant columns and rows from gtf file (gene_id and transcript_id)
gene_transcript_map <- gtf_df %>%
  filter(type == "transcript") %>%
  filter(transcript_biotype == "protein_coding") %>% 
  dplyr::select(gene_id, transcript_id) %>%  
  distinct()

#View(gtf_df %>% filter(transcript_id == 'C53C7.5b'))

all_TPMs_with_genes <- as.data.frame(all_TPMs) %>%
  rownames_to_column("transcript_id") %>%
  filter(transcript_id %in% gene_transcript_map$transcript_id) %>%
  left_join(gene_transcript_map, by = "transcript_id")

filtered_TPMs <- all_TPMs_with_genes %>%
  filter(transcript_id %in% rownames(long_transcripts))


major_tr_list <- list()

for (i in names(samples_dict)) {
  print(i)
  major_tr <- filtered_TPMs %>%
  #filter(colname > 1000) %>%
  group_by(gene_id) %>%
  mutate(mean_TPM = rowMeans(across(ends_with(i)))) %>%
  filter(mean_TPM > 1) %>%
  slice_max(order_by = mean_TPM, n = 1, with_ties = FALSE)
  
  major_tr_list <- append(major_tr_list, list(major_tr[, c('transcript_id', 'mean_TPM','gene_id')]))
}

names(major_tr_list) <- names(samples_dict)
names(major_tr_list)
```

```{r}
# quantifying cryptic transcription with exon read counts (from featureCounts)

common_path <- '/cellfile/datapublic/ahyseni/cryption/c.elegans/docker/featureCounts/output/'


gene_slopes <- data.frame()

for (i in names(samples)) {
  print(i)
  print(samples[i])
  path <- paste0(common_path, samples[i],'/', i, '/exon_counts.txt')
  
  exon_counts <- read.delim(path, comment.char = "#")
  colnames(exon_counts)[7] <- 'bam_counts'
  
  exon_counts <- exon_counts %>% 
    mutate(., normalized_counts = (bam_counts / (Length/1000))) %>% 
    mutate(., seq_depth = sum(normalized_counts)) %>% 
    mutate(., EPM = normalized_counts * ((10^6)/seq_depth)) %>% 
    group_by(Geneid) %>%
    mutate(Exon = row_number()) %>% 
    filter(Exon != 1 & Exon != n()) %>% 
    mutate(new_Start = ifelse(Strand == "+", Start - Start[1], (Start - End[1]) * (-1))) %>% 
    mutate(new_End = ifelse(Strand == "+", End - Start[1], (End - End[1]) * (-1))) %>% 
    mutate(Middle_Exon = (new_Start + new_End)/2)

  gene_slope1 <- exon_counts %>%
    group_by(Geneid) %>%
    #filter(Geneid %in% major_tr_list$ama1$transcript_id) %>% 
    summarise(slope = lm(EPM ~ Middle_Exon) %>% coef() %>% .[2]) %>% 
    rename(slope = paste0('slope_', samples[i], '_', i))
  
  if (nrow(gene_slopes) == 0) {
    gene_slopes <- gene_slope1 
  } else {
    gene_slopes <- full_join(gene_slopes, gene_slope1, by = "Geneid")
  }
}


compare_wt_ama1 <- gene_slopes %>% 
  dplyr::select(., Geneid, slope_wt_K002000093_54873, slope_ama1_K002000093_54879) %>% 
  filter(Geneid %in% intersect(major_tr_list$wt$transcript_id, major_tr_list$ama1$transcript_id)) %>% 
  mutate(difference = slope_ama1_K002000093_54879 - slope_wt_K002000093_54873)

hist(compare_wt_ama1$difference)


exon_counts <- read.delim(paste0(common_path, 'ama1/K002000093_54879/exon_counts.txt'), comment.char = "#")
colnames(exon_counts)[7] <- 'bam_counts'

exon_counts <- exon_counts %>% 
  mutate(., normalized_counts = (bam_counts / (Length/1000))) %>% 
  mutate(., seq_depth = sum(normalized_counts)) %>% 
  mutate(., EPM = normalized_counts * ((10^6)/seq_depth)) %>% 
  group_by(Geneid) %>%
  mutate(Exon = row_number()) %>% 
  filter(Exon != 1 & Exon != n()) %>% 
  mutate(new_Start = ifelse(Strand == "+", Start - Start[1], (Start - End[1]) * (-1))) %>% 
  mutate(new_End = ifelse(Strand == "+", End - Start[1], (End - End[1]) * (-1))) %>% 
  mutate(Middle_Exon = (new_Start + new_End)/2)

gene_slopes <- exon_counts %>%
  group_by(Geneid) %>%
  #filter(Geneid %in% major_tr_list$ama1$transcript_id) %>% 
  summarise(slope = lm(EPM ~ Middle_Exon) %>% coef() %>% .[2])

gene_slopes$slope %>% na.omit() %>% mean()

```

